// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numTrials = Integer.parseInt(args[0]);
		double bigger = 0.0;
		double smaller = 0.0;
	for (int  i  =  0;  i  <  numTrials;  i++)  {
		double num = Math.random();

		if (num > 0.5){
			bigger++;
		} else {
			smaller++;
		}
	}
		double ratio = 0.0 ;
		if (smaller == 0) {
			System.out.println( "0 cannot divide by zero" );
		} else {
			ratio = bigger / smaller;
		}
		int newBigger = (int)bigger;
		int newSmaller = (int)smaller;
			System.out.println("> 0.5: " + newBigger + " times");
			System.out.println("<= 0.5: " + newSmaller + " times");
			System.out.println("Ratio: " + ratio);
		}


	}
